In [ ]:
import numpy as np

In [ ]:
# create the numpy array with random numbers

arr = np.array([30, 1, 4, 29, 44, 12, 10, 3, 8, 2])
print(arr)

[30  1  4 29 44 12 10  3  8  2]


In [ ]:
np.sort(arr)

array([ 1,  2,  3,  4,  8, 10, 12, 29, 30, 44])

In [ ]:
# i want to concatenate two numpy arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# create array with the shape (3, 2, 4) with static values

arr = np.array([
                [[1, 2, 3, 4], [5, 6, 7, 8]],
                [[9, 10, 11, 12], [13, 14, 15, 16]],
                [[17, 18, 19, 20], [21, 22, 23, 24]]
              ])

In [ ]:
arr.ndim

3

In [ ]:
arr.size

24

In [ ]:
arr.shape

(3, 2, 4)

In [ ]:
# lets reshape to 2, 2, 4

arr.reshape(2, 2, 4)

ValueError: cannot reshape array of size 24 into shape (2,2,4)

In [ ]:
arr.reshape(2, 2, 6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [ ]:
# create 1d array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.shape

(12,)

In [ ]:
# convert 1d array to 2d array

arr.reshape(4, 3).ndim

2

In [ ]:
# convert 1d array to 2d array, i want to add extra axis using np.newaxis

a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
a2 = a[np.newaxis, :]

a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# lets do the demo with np.expand_dims

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)

b = np.expand_dims(a, axis=1)
print(b.shape)
print(b)

(6,)
[1 2 3 4 5 6]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
