In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([9, 8, 5,2,1])

In [3]:
a3 = np.concatenate(a1, a2)

TypeError: only integer scalar arrays can be converted to a scalar index

In [4]:
a3 = np.concatenate([a1, a2])

In [5]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [6]:
data[0]

1

In [7]:
data[0:6:2]

array([1, 3, 5])

In [8]:
data[-1]

12

In [13]:
a = np.array([[1,2,3,4], [5,1,7,8], [9,10,11,12]])
a[a < 5]
print(a.shape)

(3, 4)


In [11]:
five_and_up = (a >= 5)
print(a[five_and_up])

[ 5  7  8  9 10 11 12]


In [12]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  8 10 12]


In [17]:
bool_lnd = a[(a > 2) & (a < 11)]
print(bool_lnd)
print(a)

[ 3  4  5  7  8  9 10]
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10 11 12]]


In [18]:
bool_lor = a[(a < 5) | (a > 10)]
print(bool_lor)
print(a)

[ 1  2  3  4  1 11 12]
[[ 1  2  3  4]
 [ 5  1  7  8]
 [ 9 10 11 12]]


In [19]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True False  True  True]
 [ True  True  True  True]]


In [29]:
a = np.array([[1,2,3,4], [5,1,7,8], [9,10,11,12]])
a[1:2,1:3]

array([[1, 7]])

In [30]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0, 1]), array([0, 1, 2, 3, 1]))


In [25]:
print(a[b])

[1 2 3 4 1]


In [31]:
a[0, 0]

1

In [32]:
a[0, 1]

2

In [53]:
a1 = np.array([[ 1, 3],[ 5, 7],[3,3]])

a2 = np.array([ [4, 2], [6, 8],[9,9]])

print(a1.shape)
print(a2.shape)

r1 = np.vstack((a1, a2))
print(r1.shape)
print(r1)

print(np.concatenate((a1, a2)))

(3, 2)
(3, 2)
(6, 2)
[[1 3]
 [5 7]
 [3 3]
 [4 2]
 [6 8]
 [9 9]]
[[1 3]
 [5 7]
 [3 3]
 [4 2]
 [6 8]
 [9 9]]


In [40]:
r2 = np.hstack((a1, a2))
print(r2)
print(r2.shape)

[[1 3 4 2]
 [5 7 6 8]]
(2, 4)


In [41]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [44]:
sp1 = np.hsplit(x, 3)
print(sp1)

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]


In [45]:
sp2 = np.hsplit(x, (3, 4))
print(sp2)

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]
