In [1]:
import numpy as np

In [8]:
data = np.array([1, 2])
ones = np.ones(2, dtype = int)

In [10]:
data + ones

array([0, 1])

In [5]:
data.shape

(2,)

In [11]:
data - ones

array([0, 1])

In [12]:
data * ones

array([1, 2])

In [13]:
data / ones

array([1., 2.])

In [14]:
a = np.array([1, 2, 3, 4])

In [15]:
a.sum()

10

In [26]:
b = np.array([[-1, 2], [3, 2]])

In [32]:
b.sum(axis = 1)

array([1, 5])

In [33]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 8])

c = a + b
print(c)

[[ 8 10 11]
 [11 13 14]]


In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1], [2]])

c = a * b

print(c)

[[ 1  2  3]
 [ 8 10 12]]


In [41]:
# array with static values with shape 3 x 4 with float values between 0 to 1, dont use random function

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [44]:
(a.sum(), a.min(), a.max() )

(4.8595784, 0.05093587, 0.82485143)