In [1]:
import numpy as np

In [3]:
# today we will see matrices in numpy

# https://en.wikipedia.org/wiki/Matrix_(mathematics)

data = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
  ])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
data[0, 1]

2

In [5]:
data[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
data[0:2, 0]

array([1, 4])

In [7]:
(data.min(), data.max(), data.sum(), data.mean())

(1, 9, 45, 5.0)

In [8]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [9]:
np.dot(data, ones)

array([[3, 3],
       [7, 7]])

In [14]:
rng = np.random.default_rng()
rng.random(3)

array([0.33404736, 0.7366441 , 0.10734134])

In [20]:
rng.integers(5, size=(2, 4))

array([[2, 4, 2, 0],
       [4, 3, 2, 3]])

In [21]:
a = np.array([11, 11, 34, 12, 13, 14, 15, 17, 13, 12, 11, 14, 18, 19, 20])

In [22]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 17 18 19 20 34]


In [23]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  3  4  5  6  7 12 13 14  2]


In [25]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)
print(unique_values)

[3 2 2 2 1 1 1 1 1 1]
[11 12 13 14 15 17 18 19 20 34]


In [30]:
a_2d = np.array([[1,2,3,4], [5,6,7,2], [9,10,11,12], [1,2,3,4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  9 10 11 12]


In [31]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  2]
 [ 9 10 11 12]]


In [33]:
data = np.array([
    [1,2,3],
    [4,5,6],
])

In [34]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
arr = np.arange(6)

In [38]:
print(arr)

[0 1 2 3 4 5]


In [43]:
reshaped = arr.reshape(2, 3)
print(reshaped)

[[0 1 2]
 [3 4 5]]


In [44]:
reshaped.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [45]:
reshaped.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [46]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
reversed = np.flip(arr)
print(reversed)

[8 7 6 5 4 3 2 1]


In [55]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [52]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [53]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [54]:
np.flip(arr_2d, axis = 1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [58]:
(arr_2d.ndim, arr_2d.size, arr_2d.shape)

(2, 12, (3, 4))

In [64]:
flat_arr = arr_2d.ravel()
print(flat_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [65]:
flat_arr[1] = 100
print(flat_arr)
print(arr_2d)

[  1 100   3   4   5   6   7   8   9  10  11  12]
[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
