In [2]:
import numpy as np

In [3]:
def mse(y_true, y_pred):
    return np.mean(np.power(y_true - y_pred, 2))

In [4]:
def mse_as_it(pred, labels):
    return (1/len(labels)) * np.sum((pred - labels)**2)

In [5]:
mse_lmd = lambda y_true, y_pred: np.mean(np.power(y_true - y_pred, 2))

In [6]:
y_true = np.array([1, 1, 2, 3])
y_pred = np.array([0, 2, 2, 2])

print(mse(y_true, y_pred))
# print(mse_as_it(y_pred, y_true))
# print(mse_lmd(y_true, y_pred)

0.75


In [8]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('a', a)

In [11]:
b = np.load('a.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
csv_arr = np.array([1, 2, 3, 4])
np.savetxt('csv_arr.csv', csv_arr)

In [13]:
np.loadtxt('csv_arr.csv')

array([1., 2., 3., 4.])